### ISSUE TITLE
Link to Race to the Top report on homepage

### ISSUE THREAD

**Issue by ginnyfahs** [TheDigitalStandard/thedigitalstandard.org#12]
For the launch of Race to the Top report, we want to link to it from the homepage.

It should live above "Let's Raise the Standard" and look the same as on the ABOUT page:

<img width="652" alt="Screen Shot 2020-09-11 at 12 17 33 PM" src="https://user-images.githubusercontent.com/26640476/92949326-e79e4580-f428-11ea-9b36-cfd5ea9beeaf.png">

**Comment by benrito** [comment]
@tbeck can we hide this in CSS for now, and come back / re-open when the report is ready?

Thank you!

**Comment by tbeck** [comment]
@benrito - this CTA is hidden on the about page for now. https://polite-moon.cloudvent.net/about/
