### ISSUE TITLE
Enable gh-pages for hosting version endpoints

### ISSUE THREAD

**Issue by tbeck** [TheDigitalStandard/thedigitalstandard.org#13]
@benrito 
I've added a Github workflow that will control version build and deployment. 
[commit](e005dee66d357e5a4475eaadf63cec28342c1854)

We will need to enable Github pages for this repository in order to host these version endpoints.
https://github.com/TheDigitalStandard/thedigitalstandard.org/commits/gh-pages

Thanks!

**Comment by benrito** [comment]
Hi @tbeck , sounds good. Which branch should we use? Made you admin too.

**Comment by tbeck** [comment]
Hi @benrito 
I've enabled Github pages and am pointing to the default gh-pages branch for now.

Here is the current version endpoint we are using for testing: 
https://thedigitalstandard.github.io/thedigitalstandard.org/v0.0.1/

We can add a custom domain at any point if needed.

Endpoints are automatically built and deployed when a release/tag is pushed in Github. I'd like to step through the custom action ([here](https://github.com/TheDigitalStandard/thedigitalstandard.org/blob/master/.github/workflows/release.yml)) we have written to accomplish this with you and confirm that this falls inline with your needs for managing releases/versions.

Thanks!
