### ISSUE TITLE
Fix documentation buttons on About tab

### ISSUE THREAD

**Issue by ginnyfahs** [TheDigitalStandard/thedigitalstandard.org#17]
When I click any of the four Documentation buttons on the [About tab](https://polite-moon.cloudvent.net/about/), I see a blank screen without indicators or side navigation, like this:

![Screen Shot 2020-09-23 at 3 00 22 PM](https://user-images.githubusercontent.com/26640476/94148047-1f06ec00-fe44-11ea-9efc-a3e5913a1d8b.png)

When I use the top navigation bar on this page to switch into a different category (Security, Privacy, Ownership, or Governance) everything works fine.

**Comment by stephtngu-CR** [comment]
cc: @tbeck

**Comment by tbeck** [comment]
This should be fixed as part of this PR: #19
