### ISSUE TITLE
Could you provide us with the template / raw file you're using to generate the DS mapping? 

### ISSUE THREAD

**Issue by stephtngu-CR** [TheDigitalStandard/thedigitalstandard.org#26]
![image](https://user-images.githubusercontent.com/68969226/94704633-1d3e9c00-030e-11eb-9935-41fc6481344a.png)

**Comment by benrito** [comment]
@nickkrusick can you or Alyssa help?

**Comment by tbeck** [comment]
@benrito / @stephtngu-CR 
We have added logic to dynamically build this visual and easy control through the CMS.
#36 is the open PR. If you are okay with this feature, let me know and I can go ahead and merge this in as part of teh v1.1 milestone

Here is a link to a separate staging instance for reference:
https://gutsy-fork.cloudvent.net/case-studies/connected-cameras/#mapping

**Comment by tbeck** [comment]
Let me know if you would still like us to provide a creation file for this?

**Comment by benrito** [comment]
Wow, that is awesome! Can you walk us through the implementation today?
