### ISSUE TITLE
Align DS mapping grid to be inline with the rest of the text and images above.

### ISSUE THREAD

**Issue by stephtngu-CR** [TheDigitalStandard/thedigitalstandard.org#27]
![image](https://user-images.githubusercontent.com/68969226/94704804-4d863a80-030e-11eb-9d03-66954c8c36b6.png)

Currently the DS mapping grid takes up the full width of the screen. For consistency, could we just have it live in the parameters of the existing text and images above in the case studies? If this was intentional and the text would be too small to be readable, please feel free to close this.

**Comment by tbeck** [comment]
#36 Added logic to handle dynamic generation of this mapping grid.

The grid layout and minimum font size force us to utilize the maximum width. I am going to mark this as closed since it was intentional, but let me know if you think this deserves further conversation.
