### ISSUE TITLE
Social share image

### ISSUE THREAD

**Issue by benrito** [TheDigitalStandard/thedigitalstandard.org#29]
Can we have the logo instead? 

![Screen Shot 2020-09-30 at 11 24 38 AM](https://user-images.githubusercontent.com/541325/94705920-938fce00-030f-11eb-8eb4-a660a4a78b6e.png)

**Comment by tbeck** [comment]
We have added the following default social share image: https://polite-moon.cloudvent.net/img/TDS-SocialShare.png

**Comment by benrito** [comment]
Can you double check that tag is properly configured? It's defaulting for me to the camera image? https://socialsharepreview.com/?url=https://polite-moon.cloudvent.net/

**Comment by tbeck** [comment]
Hi @benrito - Thanks for reopening this. There was a duplicate meta tag that was causing the check to fail.

After the fix here are the results that I am getting now: https://gyazo.com/19810d84fae6705683dbd1a82f02f66a
