### ISSUE TITLE
We need a terms of service link

### ISSUE THREAD

**Issue by benrito** [TheDigitalStandard/thedigitalstandard.org#3]

**Comment by benrito** [comment]
@tbeck it will likely point to the regular CR terms of service -- can you guys help?

**Comment by tbeck** [comment]
Absolutely... should this link be added in the footer? 
Can you confirm the links that you would like to point to? I don't see a "terms of service" under the consumerreports.org site at first glance. 

- https://www.consumerreports.org/cro/2015/01/user-agreement/index.htm
- https://www.consumerreports.org/cro/customerservice/privacy-policy/highlights/index.htm

**Comment by benrito** [comment]
Hey Tom, we're going to see if we can soft launch tomorrow -- the only blocker right now is adding the ToS link. Will send a note later today...

**Comment by tbeck** [comment]
@benrito - This is up and editable through the CMS if it needs to be redirected
