### ISSUE TITLE
Additional footer links

### ISSUE THREAD

**Issue by benrito** [TheDigitalStandard/thedigitalstandard.org#33]
Hey @tbeck, I am sorry to have added this one extra ticket, but was just informed by our legal that we need to also add a footer link for:

Privacy Policy: https://www.consumerreports.org/cro/customerservice/privacy-policy/index.htm

Copyright: this will need to be a new page, is that OK? text is here: https://docs.google.com/document/d/1kURL3rdfxSkIqBn9LA-R9RzuofOSTTyXhZNyArdGgRY/edit?ts=5f74ec05

**Comment by tbeck** [comment]
@benrito - I just pushed this update, however... I am not clear on where to point the link to "Creative Commons CC BY 4.0 license"
https://polite-moon.cloudvent.net/#pageFooter

The copyright statement and links to privacy policy and terms of service are editable, but let me know if there are any additional changes we can help with?
