### ISSUE TITLE
Build process creates error

### ISSUE THREAD

**Issue by benrito** [TheDigitalStandard/thedigitalstandard.org#37]
Howdy @tbeck, any advice?

https://polite-moon.cloudvent.net/standard/

https://polite-moon.cloudvent.net/standard/security/?version=1.2.0

**Comment by benrito** [comment]
Seems fixed now; maybe there's a caching error, or something of that nature?

If we want to preflight this, we can test creating a new tagged release, to see if it happens again?

**Comment by benrito** [comment]
Can y'all also help us remove the v0.0.3 release?

**Comment by stephtngu-CR** [comment]
last commit on https://github.com/TheDigitalStandard/TheDigitalStandard/pull/167/files should populate on https://polite-moon.cloudvent.net/standard/security/?version=1.2.0#personal-safety

not seeing several commits show up on build

**Comment by tbeck** [comment]
@benrito - v0.0.3 has been removed. bb79a14

@stephtngu-CR
It looks like the commits you are referencing are on a different repository. Is the expectation that you would continue to  make updates in that repository? It might make sense to connect and discuss as this is probably related to issue #35 
I'm happy to jump on a quick call if it helps.

**Comment by tbeck** [comment]
Marking as complete.
