### ISSUE TITLE
Partners section -- more hierarchy?

### ISSUE THREAD

**Issue by benrito** [TheDigitalStandard/thedigitalstandard.org#8]

**Comment by benrito** [comment]
hey @tbeck @nickkrusick, we are going to have more partners and might want to add some hierarchy.

Right now the template is left side title, right side vertical list of logos.

Could we set up the template with a header, and two columns of logos instead?

**Comment by tbeck** [comment]
We have added a staging site for v1.1
https://sturdy-radish.cloudvent.net/contribute/
